name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: GamingHubBot/
    - name: Build
      run: dotnet build --no-restore -o deploy
      working-directory: GamingHubBot/
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        local: /home/runner/work/GamingHub-Bot/GamingHub-Bot/GamingHubBot/deploy/
        remote: ${{ secrets.REMOTE_TARGET }}
        recursive: true
        atomicPut: true
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.SSHKEY }}
